export const GET_MOVIES_HOME = "GET_MOVIES_HOME";
export const GET_MOVIE_BY_SEARCH = "GET_MOVIE_BY_SEARCH";
export const GET_MOVIES_BY_STAR = "GET_MOVIES_BY_STAR";
export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const GET_MOVIE_RELATED = "GET_MOVIE_RELATED";
export const GET_RATE_MOVIE = "GET_RATE_MOVIE";
